version: '3.9'

services:
  db-service:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: offre_emploi
      MYSQL_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
  
  eureka-server:
    image: eureka
    container_name: eureka-server
    ports:
      - "8870:8870"
    networks:
      - app-network
    depends_on:
      - db-service

  spring-server:
    image: spring-server
    container_name: spring-server
    environment:
      MYSQL_DATABASE: mysql
      SPRING_DATASOURCE_URL: "jdbc:mysql://db-service:3306/offre_emploi?createDatabaseIfNotExist=true"

    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db-service
      - eureka-server
  
  auth-service:
    image: auth-server
    container_name: auth-service
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db-service
      - eureka-server
    environment:
      - DEBUG=1
      - DB_HOST=db-service
      - DB_PORT=3306
      - DB_NAME=offre_emploi
      - DB_USER=root
      - DB_PASSWORD=root

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
